Part2 completed
xdie44/PFMCPP_Project6 pull request #2
Opened 2020-09-19 12:27 UTC by xdie44

2020-09-19 19:47 UTC, matkatmusic requested changes

2020-09-19 19:47 UTC, matkatmusic commented on main.cpp
> +
Fix this indentation.
- [ ] revise

2020-09-19 19:47 UTC, matkatmusic commented on main.cpp
> +    float function(float& updatedVal)      //12
Since you're not modifying `updatedVal`, this should be `const float&`, but `const` hasn't been covered yet, so no need to revise it.  just be aware.

2020-09-19 19:47 UTC, matkatmusic commented on main.cpp
> +    static float function(U& that, float& updatedVal )        //10
Since you're not modifying `updatedVal`, this should be `const float&`, but `const` hasn't been covered yet, so no need to revise it.  just be aware.

2020-09-20 00:24 UTC, xdie44 commented on main.cpp
> +    static float function(U& that, float& updatedVal )        //10
Ok got it. I changed it to 'const float&' anyway.

2020-09-20 00:24 UTC, xdie44 commented on main.cpp
> +    float function(float& updatedVal)      //12
Ok got it. I changed it to 'const float&'  anyway.

2020-09-20 18:54 UTC, matkatmusic approved these changes

2020-09-20 18:54 UTC, merged